### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by ezra-lieblich** [cloudfoundry-incubator/cli-plugin-repo#80]
I’m trying to submit my plugin into CF plugins repository but I’m having trouble with the instructions specifically the repo-index.yml and the binaries. I’m unsure how to produce a binary with a url and checksum as well as how to even cross-compile it. Here is a link to my plugin https://github.com/ezra-lieblich/safe-scale <https://github.com/ezra-lieblich/safe-scale>. I was wondering if maybe I was missing some folder or file that would help produce binaries.

**Comment by luan** [comment]
Hi @ezra-lieblich,

I'm going to split your question in 3 parts:
* How to cross-compile to the 3 different operating systems
* How to compute the checksums  (to add it to `repo-index.yml`)
* How to get a URL for the binary (to add it to `repo-index.yml`)

#### How to cross-compile to the 3 different operating systems

Golang supports cross compilation to several systems and architectures. Theres an in-depth article by Dave Cheney [here](http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5) explaining how to do it and how it works. You can also find a list of supported systems and architectures [here](https://golang.org/doc/install/source#environment) under the `$GOOS and $GOARCH` section.

The CF cli supports 5 combinations:
* `linux`/`386` (known as `linux32`)
* `linux`/`amd64` (known as `linux64`)
* `windows`/`386` (known as `win32`)
* `windows`/`amd64` (known as `win64`)
* `darwin `/`amd64` (known as `osx`)

And at a minimum we want plugins to support `linux64`, `win64` and `osx`.

So, with all that, you can generate those binaries for your plugin with the following snippet:

```bash
PLUGIN_PATH=$GOPATH/src/github.com/ezra-lieblich/safe-scale
PLUGIN_NAME=$(basename $PLUGIN_PATH)

cd $PLUGIN_PATH
GOOS=linux GOARCH=amd64 go build -o ${PLUGIN_NAME}.linux64
GOOS=linux GOARCH=386 go build -o ${PLUGIN_NAME}.linux32
GOOS=windows GOARCH=amd64 go build -o ${PLUGIN_NAME}.win64
GOOS=windows GOARCH=386 go build -o ${PLUGIN_NAME}.win32
GOOS=osx GOARCH=amd64 go build -o ${PLUGIN_NAME}.osx
```

#### How to compute the checksums

Checksums in the `repo-index.yml` file are used to verify the integrity of the binaries, to prevent corrupted downloads from being installed. We use the [`sha-1`](https://en.wikipedia.org/wiki/SHA-1) checksum algorithm, you can compute it with: `shasum -a 1 <myfile>`

So continuing the above snipped you'd do:

```bash
shasum -a 1 ${PLUGIN_NAME}.linux64
shasum -a 1 ${PLUGIN_NAME}.linux32
shasum -a 1 ${PLUGIN_NAME}.win64
shasum -a 1 ${PLUGIN_NAME}.win32
shasum -a 1 ${PLUGIN_NAME}.osx
```

Take note of those so that you can put them on `repo-index.yml` later when you have uploaded the binaries.

#### How to get a URL for the binary

You could use whatever file hosting you like here, the easiest and recommended one is GitHub releases, given that your plugin's code is already hosted on GitHub it might be the easiest solution too.

You can read more about GitHub Releases [here](https://help.github.com/articles/creating-releases/) but for the purposes of releasing your plugin you should upload those five binaries generated above on the same release.

You should then copy the resulting links for the uploaded binaries from the release page and put them on the `repo-index.yml` file.

This process can get a little tedious if you do it manually every time, that's why some plugin developers have automated it. You can probably put together scripts based on the snippets above to automate compiling, generating checksums and uploading the release to GitHub. There are tools available to manage GitHub releases such as [this one](https://github.com/aktau/github-release).

Let me know if there's anything else I can help with.

Thanks,
Luan

**Comment by luan** [comment]
I also added these instructions to the README here: https://github.com/cloudfoundry-incubator/cli-plugin-repo/blob/master/README.md#releasing-plugins
